export const PROJECTS = [
  {
    id: 'insurance-policy',
    featured: true,
    year: '2024',
    title: 'Insurance Policy Software',
    tagline: 'AI-driven document comparison for BFL Canada',
    description:
      'Enterprise web application that automates the comparison of insurance policy documents using an AI-driven discrepancy detection pipeline, collapsing a slow manual process into a fast, auditable workflow.',
    highlights: [
      'Built React / Node / MySQL stack that ingests and compares 100+ policy documents monthly.',
      'Discrepancy engine combines GROBID text extraction with Levenshtein-distance scoring via AI APIs.',
      'End-to-end testing with Playwright + Jest pushed coverage to 60% before production rollout.',
    ],
    technologies: ['React', 'Node.js', 'Express', 'MySQL', 'GROBID', 'AI APIs'],
    projectLink: 'https://github.com/COSC-499-W2024',
    image: '/assets/icons/BFL.png',
    metric: { value: '80%', label: 'faster review time' },
    accent: 'gold',
  },
  {
    id: 'jersey-recognition',
    featured: true,
    year: '2025',
    title: 'Jersey Number Recognition',
    tagline: 'Deep-learning pipeline for sports vision',
    description:
      'Enhanced an existing jersey-number recognition pipeline through aggressive data augmentation and a MixUp label-blending strategy, materially lifting classifier accuracy on low-quality frames.',
    highlights: [
      'Redesigned the legibility classifier with real-world distortions + random noise augmentations.',
      'MixUp soft-target training cut illegible-frame false positives by 25%.',
      'Shipped as a drop-in upgrade to the existing PyTorch + OpenCV pipeline.',
    ],
    technologies: ['PyTorch', 'TensorFlow', 'OpenCV', 'Pandas', 'MixUp'],
    projectLink: 'https://github.com/MahmoudOsama97/jersey-number-pipeline_PlusPlus',
    image: '/assets/icons/sys_arch.png',
    metric: { value: '+18%', label: 'classifier accuracy' },
    accent: 'cyan',
  },
  {
    id: 'portfolio',
    featured: true,
    year: '2026',
    title: 'JagtapWorks Portfolio',
    tagline: 'The site you are looking at right now',
    description:
      'A refactored Vite + React + Three.js portfolio built on the Midnight Observatory design system. Two-layer starfield, a 3D hero "Constellation of Thought", categorized skills, planetary testimonials — shipped on Cloudflare Pages.',
    highlights: [
      'Named Three.js imports + manual chunks drop initial bundle by ~40%.',
      'Sprite-based starfield at 30fps cap — ~10× CPU reduction versus the old per-frame renderer.',
      'Lighthouse scores 95+ across Performance, Accessibility, Best Practices, and SEO.',
    ],
    technologies: ['React', 'Vite', 'Tailwind', 'Three.js', 'GSAP', 'Cloudflare Pages'],
    projectLink: 'https://github.com/atharvaj0gtap/Portfolio',
    image: '/assets/logos/JagtapWorksLogo.png',
    metric: { value: '95+', label: 'Lighthouse score' },
    accent: 'gold',
  },
  {
    id: 'ai-trend',
    featured: false,
    year: '2025',
    title: 'AI Trend Analysis',
    description:
      'Python data pipeline and report analyzing the impact of AI on employment across 500 job roles and 50+ countries, with policy recommendations for reskilling.',
    technologies: ['Python', 'Pandas', 'NumPy', 'Matplotlib', 'Seaborn'],
    projectLink: 'https://github.com/atharvaj0gtap/AI-Trend-Analysis',
    image: '/assets/icons/AI.png',
    metric: { value: '500+', label: 'roles analyzed' },
  },
  {
    id: 'wildfire',
    featured: false,
    year: '2024',
    title: 'Network Analysis of Wildfires',
    description:
      'R-based network study on how environmental factors shape wildfire clustering in Alberta — Louvain, DBSCAN, and K-Means surfaced 69 communities and a 70% heat-to-size correlation.',
    technologies: ['R', 'DBSCAN', 'K-Means', 'Louvain', 'ggplot2'],
    projectLink: 'https://github.com/atharvaj0gtap/Network-Science-Team-4',
    image: '/assets/icons/NetworkAnalysis.png',
    metric: { value: '69', label: 'clusters identified' },
  },
  {
    id: 'hci-bubble',
    featured: false,
    year: '2024',
    title: 'Adaptive Bubble Cursor',
    description:
      'Unity + C# HCI study on context-aware cursor resizing in dense environments. 20-person controlled trial validated a 47% drop in selection errors (p < .01).',
    technologies: ['Unity', 'C#', 'ANOVA'],
    projectLink: 'https://github.com/atharvaj0gtap/COSC-441-Group-5',
    image: '/assets/icons/HCI.jpg',
    metric: { value: '-47%', label: 'selection errors' },
  },
  {
    id: 'learning-layers',
    featured: false,
    year: '2024',
    title: 'E-Learning Platform',
    description:
      'AI-enhanced classroom platform with course enrollment, assignment submission, and profile management. 5-person team, 8 two-week sprints, 95% MVP delivered.',
    technologies: ['React', 'Express', 'MongoDB', 'Bootstrap'],
    projectLink: 'https://github.com/dabby04/TheLearningLayers',
    image: '/assets/icons/LearningLayers.png',
    metric: { value: '95%', label: 'MVP shipped' },
  },
  {
    id: 'shelter-finder',
    featured: false,
    year: '2023',
    title: 'Shelter Finder App',
    description:
      'Android application listing emergency shelters during wildfires, with real-time geolocation and Google Maps routing — 1.2 min faster shelter-finding in simulated drills.',
    technologies: ['Android', 'Java', 'Firebase', 'Google Maps API'],
    projectLink: 'https://github.com/atharvaj0gtap/ShelterFinderApp',
    image: '/assets/icons/ShelterFinder.png',
    metric: { value: '1.2min', label: 'faster response' },
  },
  {
    id: 'ecommerce',
    featured: false,
    year: '2023',
    title: 'SwiftShopper eCommerce',
    description:
      'Java + JSP + SQL online store with UML-modeled schema, real-time order status, and one-click checkout. Inventory discrepancy down 25%.',
    technologies: ['Java', 'JSP', 'JDBC', 'SQL'],
    projectLink: 'https://github.com/atharvaj0gtap/Web-development',
    image: '/assets/icons/SwiftShopper.png',
    metric: { value: '-25%', label: 'inventory errors' },
  },
  {
    id: 'happiness',
    featured: false,
    year: '2022',
    title: 'World Happiness Analysis',
    description:
      'Multivariate regression and cluster analysis across 150+ countries in the World Happiness Index, paired with an interactive Tableau dashboard for stakeholders.',
    technologies: ['Python', 'Tableau', 'Pandas', 'Seaborn'],
    projectLink: 'https://github.com/ubco-W2022T1-cosc301/project-group41',
    image: '/assets/icons/WorldHappiness.png',
    metric: { value: '150+', label: 'countries studied' },
  },
];
